#########################
# Script to be executed #
#########################
executable            		= script.sh

#############################################################
# How many times to retry the job if success_exit_code <> 0 #
#############################################################
#max_retries = 3

##########################################################
# Definition of output,error,log files (The directories  # 
# output,error and log should have already been created) #
##########################################################
output                		= output/CUETP8M1_$(ClusterId)$(ProcId).out
error                 		= error/CUETP8M1_$(ClusterId)$(ProcId).err
log                   		= log/CUETP8M1_$(ClusterId).log

######################
# Transferring files #
######################
should_transfer_files           = YES

##################################################
# Input files need to be transferred to the node #
##################################################
transfer_input_files 		= rivet_InclusiveJets_QCD_Pt-15To7000_TuneCUETP8M1_Flat_13TeV-pythia8_cfg.py

###########################################################
# Output files to the submit machine (Default is ON_EXIT) #
# ON_SUCCESS means if the success_exit_code=0             #
###########################################################
#when_to_transfer_output         = ON_SUCCESS
when_to_transfer_output         = ON_EXIT

######################################################################
# Enviromental variables for the script --> seed and output filename #
######################################################################
environment           		= seed=$(ClusterId)$(ProcId);yodafile=CUETP8M1_seed_$(ClusterId)$(ProcId).yoda

#############################
# Job flavor definition:    #
# espresso     = 20 minutes # 
# microcentury = 1 hour     #
# longlunch    = 2 hour     #
# workday      = 8 hour     #
# tomorrow     = 1 day      #
# testmatch    = 3 days     #
# nextweek     = 1 week     #
#############################
+JobFlavour           		= "workday"

####################################################################
# Number of jobs to be submitted with queue command (Default is 1) #
####################################################################
queue 100
